

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    environment:
      - APP_ENV=dev
      - APP_SECRET=ea6f44a8c1aff88214ae639b39c56ec0
      - DATABASE_URL=postgresql://app:ChangeMe!@database:5432/app?serverVersion=16&charset=utf8
      - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
      - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
      - JWT_PASSPHRASE=afcdfde1f93abd4b94939b98e0a5557d7c59599d400209a5bee214e0a703b07a
      - CORS_ALLOW_ORIGIN=^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "
        php bin/console cache:clear &&
        php bin/console doctrine:migrations:migrate --allow-no-migration --no-interaction &&
        php bin/console app:create-user test@example.com password --no-interaction &&
        php-fpm
      "

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/public
    depends_on:
      - backend

  frontend:
    build:
      context: ./vehicle-service-invoice-generator
      dockerfile: Dockerfile
    volumes:
      - ./vehicle-service-invoice-generator:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: ChangeMe!
      POSTGRES_USER: app
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=ChangeMe! pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  database_data: